### ISSUE TITLE
Name mismatch: "Greenwatch Initiate"

### ISSUE THREAD

**Issue by johncarney** [MrPrimate/pathmuncher#10]
**Describe the bug**
This is not exactly a Pathmuncher bug, but Pathbuilder misspells the "Greenwatch Initiate" feat as "Green Watch Initiate." I've reported the issue with Pathbuilder, but it would be nice if Pathmuncher could match it.

**To Reproduce**
1. Create a Ranger, Gunslinger, or Investigator character in Pathbuilder.
2. Take it up to Level 4.
3. Select the "Green Watch Initiate" feat.
4. Export the character, noting the JSON ID.
5. Create a blank Actor in Foundry with the Pathmuncher module installed and enabled.
6. Import the character using the JSON ID recorded above.
7. When the import is complete you will get a message saying that it could not match "Green Watch Initiate" (see screenshot below).

**Expected behavior**
I would like Pathbuilder's "Green Watch Initiate" feat to be matched to the official "Greenwatch Initiate" feat.

**Screenshots**
<img width="423" alt="image" src="https://user-images.githubusercontent.com/322950/236693576-79200c66-f036-40d5-a1e7-ab92398d56f8.png">

**Environment:**
 - Browser: Any
 - Foundry Version: 10.291
 - Pathfinder System Version: 4.11.2
 - Module Version: 0.4.0
 - Does this behaviour occur with other modules disabled: n/a

**Additional context**
No additional context.

**Comment by MrPrimate** [comment]
Fixed in v0.4.1 please let me know if you come across any other name mismatches.
