### ISSUE TITLE
Error on Import

### ISSUE THREAD

**Issue by DrDoom1446** [MrPrimate/pathmuncher#14]
When importing a character from Pathbuilder2e (android), A secondary actor is created and deleted but the original sheet is not updated, remaining blank. The import dialog is stuck on "Cooking (Equipment)". I am using some 3rd party feats (everything shields) but all my equipment is core. The error log is saying cant read properties of undefined, so it is hard to tell what part it is having problems with. Even unchecking all the import options except my name still fails.

To Reproduce

Create a character using Pathbuilder2e
Click on Export
Export as JSON
Note export number
Enter export number into Pathmuncher dialog
Click import
Expected behavior
Character values should be imported from Pathbuilder and copied into Foundry PF2 actor sheet

Environment:

Chrome

Foundry Version 10.291

Pathfinder System Version 4.12.5

Module Version 0.5.1

Does this behaviour occur with other modules disabled: Yes

In Pathbuilder please got to Export -> "Share Copy of Character" and provide the link.
https://pathbuilder2e.com/launch.html?build=435733

Details of any errors in the browser console (press F12).
[pathmuncher.log](https://github.com/MrPrimate/pathmuncher/files/11619591/pathmuncher.log)

**Comment by MrPrimate** [comment]
This imports for me (although with some parsing errors, which I will take a look at), but I don't get the same problem as yourself - when you export can you use the option to get the json file, then copy the contents here? Wondering if there is a slight difference between the web and android versions.

**Comment by DrDoom1446** [comment]
[import.txt](https://github.com/MrPrimate/pathmuncher/files/11624734/import.txt)
[Second.log](https://github.com/MrPrimate/pathmuncher/files/11624737/Second.log)

Here is the json. I tried copying the json in from mobile, same issue. I also tried copying the json from the web app and also doing the ID from the web app and same issue.

**Comment by DrDoom1446** [comment]
Updated to 4.12.6 and still having the issue.

**Comment by MrPrimate** [comment]
Can you try on the latest version of Pathmuncher (v0.5.4) this might be a bug with the containers on v0.5.1

**Comment by DrDoom1446** [comment]
That was the fix, thanks for all the help!
