### ISSUE TITLE
Auto install Pathmuncher when updating my modules

### ISSUE THREAD

**Issue by Jensenator360** [MrPrimate/pathmuncher#16]
Whenever I update my modules, it automatically installs "Pathmuncher. I don't use Pathfinder 2e at all and have never installed that system or the module. Even when uninstalling, it always reinstall.

**Comment by Jensenator360** [comment]
I found out it is Note Licker! After uninstalling both modules, it never reinstall.

**Comment by MrPrimate** [comment]
Thanks for the report, I must have a bad something in a json, will get it fixed, sorry!

**Comment by MrPrimate** [comment]
Hopefully this is fixed now, not sure what was the actual cause though!

**Comment by MrPrimate** [comment]
Fixed with the latest NoteLicker
