### ISSUE TITLE
Inventories for Tiny characters are imported as Medium-sized

### ISSUE THREAD

**Issue by King-Wedgie** [MrPrimate/pathmuncher#17]
**Describe the bug**
Inventories for Tiny characters (usually Sprites, or Poppets with the Toy Poppet heritage) that are exported from Pathbuilder and then imported into Foundry with Pathmuncher have their items imported as Medium sized. This results in a few conflicts (overencumbered inventories, can't wield weapons properly, etc.) due to how Tiny characters work in Pathfinder.

**To Reproduce**
Import a Tiny character from Pathbuilder as normal (export to JSON, import with Pathmuncher).

**Expected behavior**
Inventories should import with items set to Tiny size to avoid conflicts. (Funnily enough, items dragged over from compendiums automatically resize for Tiny characters, but items dragged from the directory retain their set size - usually Medium.)

**Screenshots**
![image](https://github.com/MrPrimate/pathmuncher/assets/73143074/cf487aec-1927-4b35-a2a6-49f424884d2f)

**Environment:**
 - Browser: Firefox 114.0.2 (64-bit)
 - Foundry Version v10.291
 - Pathfinder System Version v4.12.9
 - Module Version v0.7.2
 - Does this behaviour occur with other modules disabled: Yes

**Additional context**

 - In Pathbuilder please got to Export -> "Share Copy of Character" and provide the link.
 https://pathbuilder2e.com/launch.html?build=455784

 - Details of any errors in the browser console (press F12).
 No errors.

**Comment by MrPrimate** [comment]
AH! Thanks for this, I will make changes to try and accommodate this, but it looks like there is also a bug in the JSON from Pathbuilder, so will raise that as well to get it fixed.

**Comment by MrPrimate** [comment]
I will add a work around to the next version of Pathmuncher though.

**Comment by King-Wedgie** [comment]
New update works great! Thanks.
