### ISSUE TITLE
Colour Blindness accessibility

### ISSUE THREAD

**Issue by TVandevenne** [MrPrimate/pathmuncher#18]
**Is your feature request related to a problem? Please describe.**

One of my players is colourblind and he can't see 75% of the character sheet.

**Describe the solution you'd like**

There are international standards for colours so user accessibility is high for them as well.
What the person told me is that it is mostly due to not having enough contrast between background and text.

I hope you can make an easy fix soon by fixing the colour palette or a "for now" fix by not having dark grey text on light grey backgrounds etc.

Many Thanks
Great tool otherwise

**Comment by MrPrimate** [comment]
Do you mean the pathmuncher import screen, pathbuilder itself or the pf2e character sheet?

**Comment by TVandevenne** [comment]
Hi,  thanks for the reply. It is thepf2e character sheet. I have attached a screenshot.
Many thanks 

<img width="930" alt="Screenshot 2023-06-25 214426" src="https://github.com/MrPrimate/pathmuncher/assets/111162355/6d9988ad-1a40-49f6-901b-aac9daf06457">

**Comment by MrPrimate** [comment]
Thanks, this is the repo for the Pathmuncher tool, you'll want to report this at the PF2e system project: https://github.com/foundryvtt/pf2e
