### ISSUE TITLE
Unable to Fetch a character with Pathbuilder id .......

### ISSUE THREAD

**Issue by jfrazierjr** [MrPrimate/pathmuncher#2]
1. Go to 'Actor sheet'
2. Click on 'Pathmuncher'
3. enter Pathbuilder id
4. Click Import

**Expected behavior**

**Screenshots**

**Environment:**
 - Browser Chrome
 - Foundry Version: 10.291
 - Pathfinder System: Version 4.6.8
 - Module Version: 0.0.6
 - Does this behaviour occur with other modules disabled: Did not test

A Pathbuilder export number: 304883

![image](https://user-images.githubusercontent.com/2130984/215375844-54cf772d-522b-4bac-be20-a1c4699a46ef.png)

![image](https://user-images.githubusercontent.com/2130984/215375566-e7ad836b-543f-4847-b4e8-0c304068c367.png)

also OF NOTE: one of my attempts had the console showing a DOUBLE number.    However the dialog input does not show this.   I would suggest either a plain textbox with size limit or some other means since this might be an easy thing for someone to do via pasting their number twice(which I did) and overflowing the accepted size limit:

![image](https://user-images.githubusercontent.com/2130984/215376488-d91af203-6942-4a7e-b5a8-69be9aa5ff84.png)

**Comment by MrPrimate** [comment]
This id does not work here either - have you exported the json file on the pathbuilder site?

**Comment by jfrazierjr** [comment]
I found out a bit later in a discord I belong to I was using it wrong.    I was using the Pathbuilder character id and NOT the JSON id.   I would recommend adding a quick instruction blurb since those two numbers are different.
