### ISSUE TITLE
Freeze at uploading Cooking (Weapons)

### ISSUE THREAD

**Issue by z3rglingboss** [MrPrimate/pathmuncher#20]
**Describe the bug**
Pathmuncher freezes at Cooking (Weapons) for a specific character (2nd level Champion with the free reaction Feat: Shield Block)

**To Reproduce**
1. Go to 'Import a character from Pathmuncher'
3. Click on 'Use ID'
4. Click on 'Import'
5. See error

**Expected behavior**
Character gets imported

**Screenshots**
Not sure a screenshot would help here. I'll upload browser console though. Seems like things halt when it gets to 'Shield Block'

**Environment:**
 - Browser Foundry VTT, Win10 Desktop native app
 - Foundry Version Verson 11 Build 306
 - Pathfinder System Version 5.1.2
 - Module Version 0.7.7
 - Does this behaviour occur with other modules disabled: Yes

 - In Pathbuilder please got to Export ->[ "Share Copy of Character" and provide the link.](https://pathbuilder2e.com/launch.html?build=480586)

 - Details of any errors in the browser console (press F12).
 
Foundry VTT | Created Actor with id [tHtSPj7S4zoPnGWV]
commons.js:8713 Foundry VTT | Created 13 Item documents in parent Actor [tHtSPj7S4zoPnGWV]
commons.js:8713 Foundry VTT | Deleted Actor with id [tHtSPj7S4zoPnGWV]
logger.js:53 pathmuncher | WARN > Unable to find parsed feature match for granted feature Shield Block. This might not be an issue, but might indicate feature duplication. Objectdocument: {_id: 'APTMxk5dYurSjlCL', img: 'systems/pf2e/icons/features/feats/feats.webp', name: 'Shield Block', system: {…}, type: 'feat', …}parent: effects: Array(0)length: 0[[Prototype]]: Array(0)flags: {core: {…}, pf2e: {…}}folder: nullimg: "systems/pf2e/icons/features/classes/shield-block.webp"name: "Shield Block"ownership: {default: 0}sort: 0system: {description: {…}, source: {…}, rules: Array(0), slug: 'shield-block', schema: {…}, …}type: "feat"_id: "fViidGhHhoO0Jf0N"_stats: {systemId: null, systemVersion: null, coreVersion: null, createdTime: null, modifiedTime: null, …}data: (...)permission: (...)get data: () => {…}set data: value => setProperty(data, newKey, value)get permission: () => {…}set permission: value => setProperty(data, newKey, value)[[Prototype]]: Object[[Prototype]]: Object
log @ logger.js:53
foundry.js:6549 TypeError: Cannot set properties of undefined (setting 'die')
    at #generateWeaponItems (Pathmuncher.js:1551:1)
    at async #processEquipment (Pathmuncher.js:2011:1)
    at async Pathmuncher.processCharacter (Pathmuncher.js:2206:1)
    at async PathmuncherImporter._updateObject (PathmuncherImporter.js:105:1)
    at async PathmuncherImporter._onSubmit (foundry.js:6546:7)

**Comment by MrPrimate** [comment]
Hi, thanks for the report, this is because Throwing shields are marked as weapons in pathbuilder, but come in as equipment with some fun rules in Foundry. This is fixed in v0.7.8, out now!
