### ISSUE TITLE
The Free Attributes Boosts are not imported

### ISSUE THREAD

**Issue by DrazahSuzaku** [MrPrimate/pathmuncher#21]
**Describe the bug**

**To Reproduce**
1. Go to Pathbuilder
2. Create a character with all the attributes boosts.
3. Import to Foundry
4. Click on Edit Attributes Modifier and see the Free boosts are not impoted

**Environment:**
 - Chrome
 - Foundry Version 11 Stable Build 307
 - Pathfinder System Version 5.3.1
 - Module Version 0.7.9

(https://pathbuilder2e.com/launch.html?build=495235)

**Comment by MrPrimate** [comment]
An, thank you, this is due to a change in name in the system to reflect the changes from Abilities to Attributes. I will fix it in the next release, due out in a few hours.

**Comment by MrPrimate** [comment]
Now out in v0.8.0
