### ISSUE TITLE
Kinectist import not working

### ISSUE THREAD

**Issue by mortiferus93** [MrPrimate/pathmuncher#22]
Trying to import a kinectist leads to the importer being stuck at "cooking (class)". Reason should be the lastet PF2e system update which added some changes to the class in question

Json included

[Testfried.txt](https://github.com/MrPrimate/pathmuncher/files/12475180/Testfried.txt)

**Comment by MrPrimate** [comment]
Pathmuncher is not yet compatible with the 5.4.x version of PF2e, a new version should be released in the next day or so.

**Comment by MrPrimate** [comment]
Should be fixed in v0.9.0
