### ISSUE TITLE
Skill Training feat does not import correctly

### ISSUE THREAD

**Issue by Lazzus** [MrPrimate/pathmuncher#23]
The "Skill Training" feat does not import correctly. If Society was selected to become trained using the feat, when importing it pops open a window with the title "Skill Training (Society)" and asks you to select a skill from those the character is not trained in (society is not an option). After the import finishes the character will be trained in both the skill selected in Pathbuilder and the skill selected in the pop up, and the feat will be listed as "Skill Training (\<Pathbuilder skill\>) (\<import skill\>)".

[skilltraining.txt](https://github.com/MrPrimate/pathmuncher/files/12544327/skilltraining.txt) is the JSON for a character that when imported will demonstrate the issue.
![image](https://github.com/MrPrimate/pathmuncher/assets/144301828/b4933cc3-b726-49b1-9607-323d22105f03)

Environment:

-  Browser: Firefox
-  Foundry Version: 11.308
-  Pathfinder System Version: 5.4.4
-  Module Version: 0.9.0
-  Does this behaviour occur with other modules disabled: Yes

**Comment by MrPrimate** [comment]
Can you share a copy of the character with me from within Pathbuilder

**Comment by Lazzus** [comment]
https://pathbuilder2e.com/launch.html?build=525792

**Comment by MrPrimate** [comment]
Thank you, I'll have this fixed in a release later today
