### ISSUE TITLE
Importing fails on all characters

### ISSUE THREAD

**Issue by peaceful-octopus** [MrPrimate/pathmuncher#25]
**Describe the bug**
I just updated Foundry to v11.313 and PF2e to 5.8.0, and now all imports fail with this error in the console:

```
TypeError: Cannot read properties of undefined (reading 'system')
    at #setAbilityBoosts (Pathmuncher.js:1291:1)
```

Using [this](https://pathbuilder2e.com/launch.html?build=577767) character, but all others I've tried also fail with the same error.

**To Reproduce**
1. Get JSON ID from Pathbuilder as usual.
2. Create empty character in Foundry
3. Start Pathmuncher and enter JSON ID
4. Click Import

**Expected behavior**
The character should be parsed and imported.

**Environment:**
 - Browser Chrome, Edge, Firefox
 - Foundry Version 11.313
 - Pathfinder System Version 5.8.0
 - Module Version 0.9.1
 - Does this behaviour occur with other modules disabled: Yes (All other modules disabled)

**Comment by MrPrimate** [comment]
Thanks for this report, fixed in v0.10.0, out _now_!
