### ISSUE TITLE
Weapon with Runes not being Imported 

### ISSUE THREAD

**Issue by Rayquaza1090** [MrPrimate/pathmuncher#30]
**Describe the bug**
When I try to import a weapon that has runes, it gets stuck on the weapon importation phase. 

**To Reproduce**
1. Go to (https://pathbuilder2e.com/launch.html?build=590205)
2. Click on Export to Json
3. Insert the specified number into the import
4. See failed import.

**Expected behavior**
The weapon should be imported with the runes.

**Screenshots**

https://i.imgur.com/gh5kIf9.png

**Environment:**
 - Chrome
 - Foundry Version 11 Stable 315
 - Pathfinder System Version 5.9.1
 - Module Version 0.11.1
 - Does this behaviour occur with other modules disabled: Yes

**Additional context**
I'm sorry to put this up so near an already released patch. 

 - In Pathbuilder please got to Export -> "Share Copy of Character" and provide the link. (https://pathbuilder2e.com/launch.html?build=590205)
 - Details of any errors in the browser console (press F12).
Foundry VTT | Rendering PathmuncherImporter
commons.js:8807 Foundry VTT | Created Actor with id [9clZaEqOvn3uA2j2]
commons.js:8807 Foundry VTT | Created 3 Item documents with ids: [jae29CIJG2Qg20B1,Z7QY2lKVjVlKXvLW,eKvRFu9TDyHaNrHn] in parent Actor [9clZaEqOvn3uA2j2]
commons.js:8807 Foundry VTT | Deleted Actor with id [9clZaEqOvn3uA2j2]
commons.js:8807 Foundry VTT | Created Actor with id [ZUDKUBCpuTp4P7m6]
commons.js:8807 Foundry VTT | Created 5 Item documents with ids: [jae29CIJG2Qg20B1,Z7QY2lKVjVlKXvLW,0tVy8ovaZZPbYgcv,eKvRFu9TDyHaNrHn,t02b2bnpvgQtHZrV] in parent Actor [ZUDKUBCpuTp4P7m6]
commons.js:8807 Foundry VTT | Deleted Actor with id [ZUDKUBCpuTp4P7m6]
logger.js:53 pathmuncher | WARN > Unable to find parsed feature match for granted feature Reactive Strike. This might not be an issue, but might indicate feature duplication. Object
log @ logger.js:53
warn @ logger.js:79
#createGrantedItem @ Pathmuncher.js:666
#addGrantedItems @ Pathmuncher.js:1174
commons.js:8807 Foundry VTT | Created Actor with id [WJIVo3iJcshHVpVJ]
commons.js:8807 Foundry VTT | Created 10 Item documents in parent Actor [WJIVo3iJcshHVpVJ]
commons.js:8807 Foundry VTT | Deleted Actor with id [WJIVo3iJcshHVpVJ]
commons.js:8807 Foundry VTT | Created Actor with id [U8SqbZ1NZ7lIU4V1]
commons.js:8807 Foundry VTT | Created 12 Item documents in parent Actor [U8SqbZ1NZ7lIU4V1]
commons.js:8807 Foundry VTT | Deleted Actor with id [U8SqbZ1NZ7lIU4V1]
logger.js:53 pathmuncher | WARN > Unable to find parsed feature match for granted feature Shield Block. This might not be an issue, but might indicate feature duplication. Object
log @ logger.js:53
warn @ logger.js:79
#createGrantedItem @ Pathmuncher.js:666
#addGrantedRules @ Pathmuncher.js:1083
logger.js:53 pathmuncher | WARN > Unable to find parsed feature match for granted feature Fighter Weapon Mastery. This might not be an issue, but might indicate feature duplication. Object
log @ logger.js:53
warn @ logger.js:79
#createGrantedItem @ Pathmuncher.js:666
#addGrantedItems @ Pathmuncher.js:1174
commons.js:8807 Foundry VTT | Created Actor with id [VuQCl22J3LiYmaTq]
commons.js:8807 Foundry VTT | Created 15 Item documents in parent Actor [VuQCl22J3LiYmaTq]
commons.js:8807 Foundry VTT | Deleted Actor with id [VuQCl22J3LiYmaTq]
logger.js:53 pathmuncher | WARN > Unable to find parsed feature match for granted feature Battle Hardened. This might not be an issue, but might indicate feature duplication. Object
log @ logger.js:53
warn @ logger.js:79
#createGrantedItem @ Pathmuncher.js:666
#addGrantedItems @ Pathmuncher.js:1174
logger.js:53 pathmuncher | WARN > Unable to find parsed feature match for granted feature Weapon Legend. This might not be an issue, but might indicate feature duplication. Object
log @ logger.js:53
warn @ logger.js:79
#createGrantedItem @ Pathmuncher.js:666
#addGrantedItems @ Pathmuncher.js:1174
commons.js:8807 Foundry VTT | Created Actor with id [8KgdrZKG5mtyZkKm]
commons.js:8807 Foundry VTT | Created 22 Item documents in parent Actor [8KgdrZKG5mtyZkKm]
commons.js:8807 Foundry VTT | Deleted Actor with id [8KgdrZKG5mtyZkKm]
logger.js:53 pathmuncher | WARN > Unable to find parsed feature match for granted feature Tempered Reflexes. This might not be an issue, but might indicate feature duplication. Object
log @ logger.js:53
warn @ logger.js:79
#createGrantedItem @ Pathmuncher.js:666
#addGrantedItems @ Pathmuncher.js:1174
foundry.js:6629 TypeError: Cannot set properties of undefined (setting 'value')
    at Pathmuncher.applyRunes (Pathmuncher.js:1643:1)
    at #generateWeaponItems (Pathmuncher.js:1670:1)
    at async #processEquipment (Pathmuncher.js:2151:1)
    at async Pathmuncher.processCharacter (Pathmuncher.js:2353:1)
    at async PathmuncherImporter._updateObject (PathmuncherImporter.js:104:1)
    at async PathmuncherImporter._onSubmit (foundry.js:6626:7)
_

**Comment by MrPrimate** [comment]
Thanks for the report, fixed in v0.11.2, out now.
