### ISSUE TITLE
Repair Kit not found

### ISSUE THREAD

**Issue by martynadams** [MrPrimate/pathmuncher#34]
**Describe the bug**
When munching a character that has a Repair Kit, it is not found (munch succeeds but with warning that it wasn't able to add the Repair Kit).

When I manually look to add the Repair Kit in Foundry it seems it's called Repair Toolkit there, so guessing it's just missing a mapping.

**To Reproduce**
Munch a character that has a Repair Kit in it's Gear in Pathbuilder 2e.
e.g. JSON ID 223110

**Expected behavior**
Import the character with no issues.

**Screenshots**
![image](https://github.com/MrPrimate/pathmuncher/assets/36024522/cffbf3e1-49de-44b9-8ece-c0527ca36078)

![image](https://github.com/MrPrimate/pathmuncher/assets/36024522/a0d107cb-a97c-4803-89de-76fc4cf38709)

![image](https://github.com/MrPrimate/pathmuncher/assets/36024522/c978fbaf-9556-4832-a22e-3c90d9ca5a97)

**Environment:**
 - Browser: Brave v1.61.101 (Chromium: 120.0.6099.71)
 - Foundry Version: 11.315
 - Pathfinder System Version: 5.10.5
 - Module Version: 0.11.6
 - Does this behaviour occur with other modules disabled: Yes

**Additional context**

 - In Pathbuilder please go to Export -> "Share Copy of Character" and provide the link.

https://pathbuilder2e.com/launch.html?build=611526

 - Details of any errors in the browser console (press F12).

![image](https://github.com/MrPrimate/pathmuncher/assets/36024522/4cb305fc-1d2c-4d1e-a69f-985ae3fcaaae)

**Comment by MrPrimate** [comment]
Fixed in v0.11.7
