### ISSUE TITLE
mismatch on handwraps of mighty blows

### ISSUE THREAD

**Issue by Drumar** [MrPrimate/pathmuncher#35]
Pathbuilder implements the Handwraps of Mighty blows different; as a regular item (optionally with the fundamental runes already applied) This is not a bug in Pathmuncher actually, as the implementation in Pathbuilder does not allow to add property runes as well.

Anyway, the way theyŕe implemented makes importing a character with these impossible as the item cannot be found.

**Comment by MrPrimate** [comment]
Fixed in v1.0.1. It will add the Potency and Striking runes to handwraps selected in Pathbuilder.
