### ISSUE TITLE
When trying to import character it hangs at 'Cooking (Weapon)...'

### ISSUE THREAD

**Issue by xudonax** [MrPrimate/pathmuncher#36]
**Describe the bug**

**To Reproduce**
1. Create a new actor
2. Open Actor
3. Click on Pathmuncher
4. Type in ID number of 226866
5. Click the Import button
6. It's starts processing but never completes

**Expected behavior**
The import should create a character with all of the details from Pathbuilder.

**Screenshots**
![image](https://github.com/MrPrimate/pathmuncher/assets/3049450/97fbb279-8cb4-4573-b5a4-97ee153885ea)

**Environment:**
 - Browser: Edge 120.0.2210.77 and Firefox 121.0
 - Foundry Version: 11.315
 - Pathfinder System Version: 5.11.4
 - Module Version: 1.0.1
 - Does this behaviour occur with other modules disabled: Yes

**Additional context**
The characters have no potency rune or anything on their character. This is happening with multiple characters.

 - In Pathbuilder please got to Export -> "Share Copy of Character" and provide the link.
  - https://pathbuilder2e.com/launch.html?build=620232
 - Details of any errors in the browser console (press F12).

 TypeError: itemData.system.potencyRune is undefined
    applyRunes Pathmuncher.js:1502
    #generateWeaponItems Pathmuncher.js:1557
foundry.js:6628:15
    _onSubmit https://[foundry-url]/scripts/foundry.js:6628

**Comment by MrPrimate** [comment]
Can you double check your Pathmuncher version, as this error (and the source code lines) indicate the installed version might be quite old, and not 1.0.1 - it might even be worth uninstalling and reinstalling Pathmuncher

**Comment by xudonax** [comment]
It says 1.0.1 in the module overview but... After a hard reload it seems to work. Guess it was caching the Javascript somewhere. I'll just blame Cloudflare and thank you for your very speedy response.

Thank you and happy holidays!
