### ISSUE TITLE
Speed Boosters not applying when imported from Pathbuilder.

### ISSUE THREAD

**Issue by Wotn9** [MrPrimate/pathmuncher#37]
**Describe the bug**
When importing an Inventor with the Armor innovation and speed boosters, the speed boosters effect does not apply to a worn armor.
**To Reproduce**
1. Create an inventor on pathbuilder 2E, remaster on, and import it to foundry with the module.
2. Everything should work fine however Speed Boosters is not automatically applied as expected (+5ft) when equipping armor.

**Screenshots**
![image](https://github.com/MrPrimate/pathmuncher/assets/45216414/33ff6cdd-e4ce-419c-8e29-849bbb6ff1c2)
![image](https://github.com/MrPrimate/pathmuncher/assets/45216414/89dbdb19-2bd8-4e84-8117-aa161c23af85)
![image](https://github.com/MrPrimate/pathmuncher/assets/45216414/8c5965ba-2156-4dfc-bee5-9612383face0)

**Environment:**
 - Browser [e.g. chrome] : Brave
 - Foundry Version [e.g. 10.288] : Up to date 11.315
 - Pathfinder System Version [e.g 2.0.3] : Up to date 5.11.5
 - Module Version [e.g 3.1.21] : 1.0.2

 - In Pathbuilder please got to Export -> "Share Copy of Character" and provide the link. : https://pathbuilder2e.com/launch.html?build=626257
 - Details of any errors in the browser console (press F12).

**Comment by MrPrimate** [comment]
Thank you for your report, fixed in v1.0.3, out now.
