### ISSUE TITLE
Gradual Ability Boost Variant Rule Not Transferring to Foundry

### ISSUE THREAD

**Issue by mkniller** [MrPrimate/pathmuncher#42]
**Description**
In Foundry I am using two variant rules, Automatic Bonus Progression and Gradual Ability Boost.

In Pathbuilder, when I level up, I am selecting my new ability boost, however when I import my character from Pathbuilder into Foundry, I still have to set the Ability Boost.

**Steps To Reproduce**
1. From the menu choose Character Options and enable the two variant rules, Use GMG automatic bonus progression and Use Gamemaster Gradual Ability Boost
![image](https://github.com/MrPrimate/pathmuncher/assets/8039354/7c34fde5-dcd3-4f65-8cf6-ba05f3aae051)
2.  In Foundry enable the same two variant rules in the PF2e core rules section
3. Open the following character in Pathbuilder
    a. https://pathbuilder2e.com/launch.html?build=666480
4. Export Character
5. In Foundry import character
6. Notice that Attribute Modifiers Edit button is still blinking
7. Click the Edit button and notice that levels 2-5 is still needing 1 choice

**Expected Behavior**
When the variant rules are enabled in both Foundry and Pathbuilder, it is expected that the selected ability boosts in Pathbuilder are correctly applied in Foundry upon import.

**Screenshots**
![image](https://github.com/MrPrimate/pathmuncher/assets/8039354/5622cd03-cc90-4a1e-a8ec-9d6ff219aa90)
![image](https://github.com/MrPrimate/pathmuncher/assets/8039354/0534361e-4a9c-4c54-801b-93bb67aa8a3f)
![image](https://github.com/MrPrimate/pathmuncher/assets/8039354/03c021fa-5905-46c1-8d65-8397485b4cae)
![image](https://github.com/MrPrimate/pathmuncher/assets/8039354/ef174fcd-1ee2-44ae-9cd5-ce0bd0ef9e97)

**Environment**
Foundry v11 build 315
Module version 1.0.12
Pathfinder system version 5.13.6
Web version 79
Browser - Chrome

**Comment by MrPrimate** [comment]
Thanks for the report, fixed in 1.0.13
