### ISSUE TITLE
Last survivor (pathbuilder) vs. Lastwall Survivor (Foundry)

### ISSUE THREAD

**Issue by carfesh** [MrPrimate/pathmuncher#44]
Not sure where the right place to fix this is, I have also created an issue for Pathbuilder some time ago, however you did write something about naming differences in the README:

https://gitlab.com/doctor.unspeakable/pathbuilder-2e-web-version/-/issues/1319

My character has the background "Lastwall survivor" (Foundry), which is named "Last survivor" in Pathbuilder.

This is a current copy of my character:

https://pathbuilder2e.com/launch.html?build=692660

Thank you!

**Comment by MrPrimate** [comment]
This is very much the right place, I shall get that tweaked and fixed for you ASAP!

**Comment by MrPrimate** [comment]
Fixed in v1.0.15
