### ISSUE TITLE
Unable to import muscular exoskeleton as initial modification for inventor

### ISSUE THREAD

**Issue by Kickbut101** [MrPrimate/pathmuncher#45]
**Describe the bug**
Muscular Exoskeleton missing from Inventor Import

**To Reproduce**
1. Inventor built with power suit and the muscular exoskeleton initial modification (can use this char export if you like 245028)
2. Initial modifications for armor are missing muscular exoskeleton, see photo

**Expected behavior**
Muscular Exoskeleton is choosable

**Screenshots**
![image](https://github.com/MrPrimate/pathmuncher/assets/16029826/933fd860-e61c-49d2-a051-fc64b5c6dffb)

**Environment:**
 - Firefox 123.0.1
 - Foundry Version v11.315
 - Pf2e 5.14.3
 - Module Version 1.0.15
 - Yes

**Additional context**

https://pathbuilder2e.com/launch.html?build=694917
browser console log:
[console-export-2024-3-13_22-41-25.txt](https://github.com/MrPrimate/pathmuncher/files/14596330/console-export-2024-3-13_22-41-25.txt)

**Comment by MrPrimate** [comment]
Thankyou for the report, it was a tricky one to track down. Fixed in v1.0.16

**Comment by Kickbut101** [comment]
@MrPrimate you are a champ, thank you!
