### ISSUE TITLE
Class and Background item references are removed on import

### ISSUE THREAD

**Issue by Drental** [MrPrimate/pathmuncher#6]
**Describe the bug**
after the import of a character the class item is missing all the normal references to the class's class features, and teh background is missing the reference ot the Background feat.

The Background Feat actually works, but the reference missing on the background is irritating to me. Changing the Background on the sheet correctly removes the Skill Feat.

**To Reproduce**
1. Import a character
2. change the level to 0
3. change the level to the correct level again

alternatively
1. Import a character
2. level up

**Expected behavior**
Class Features get added on level ups and cen be refreshed with the level down -> level up method as on normal characters.

**Screenshots**
![image](https://user-images.githubusercontent.com/74384067/222670148-97c6d5ac-35e8-46b5-9664-0571ad22459e.png)
Summoner after Import
![image](https://user-images.githubusercontent.com/74384067/222670309-a2d2271e-ddc5-4007-8db3-c4b72e57f0f2.png)
Summoner on a normal Character
![image](https://user-images.githubusercontent.com/74384067/222670570-a8384fd7-2694-4c7c-bddd-284e37379ace.png)
Class features are empty and stay empty after changing levels.

**Environment:**
Foundry Virtual Tabletop: Version 10, 10.291
Game System: pf2e, 4.8.3
Active Modules: 32
Performance Mode: 2

OS: Unknown
Client: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36
GPU: ANGLE (Intel, Intel(R) UHD Graphics Direct3D11 vs_5_0 ps_5_0, D3D11)
Max Texture Size: 16384

Scene: 1618 x 1080 | Grid Size: 100 | Padding Percentage: 0
Walls: 0 | Ambient Lights: 0 | Ambient Sounds: 0 | Tiles: 0 | Tokens: 2

Actors: 47 | Items: 16 | Journal: 130 | Rollable Tables: 0 |
Playlists: 6 | Compendium Packs: 103 | Chat Messages: 2

Module Version 0.1.6
Does this behaviour occur with other modules disabled: Yes

**Additional context**

 - ID: 154595
 - export: https://pathbuilder2e.com/launch.html?build=345816
 - Details of any errors in the browser console (press F12).

Bonus issue.
![image](https://user-images.githubusercontent.com/74384067/222672745-ed39ef5b-62de-4938-a67d-248646e8fc82.png)
logger.js:60 pathmuncher | ERR > Unable to match Greater Insistent Door Knocker {pbName: 'Greater Insistent Door Knocker', qty: 1, added: false}added: falsepbName: "Greater Insistent Door Knocker"qty: 1[[Prototype]]: Object
log @ logger.js:60
error @ logger.js:83
#generateEquipmentItems @ Pathmuncher.js:983
await in #generateEquipmentItems (async)
#processEquipment @ Pathmuncher.js:1325
processCharacter @ Pathmuncher.js:1426

This may be on the system to fix, I'll get the ask in to change all the "x (greater)" to "greater x" - it can probably be handled by Pathmuncher too, but we have all the tools that we no longer need the parentheses in my biased opinion. somewhat fuzzy search rules!

**Comment by MrPrimate** [comment]
The missing references for classes and backgrounds etc should be fixed in v0.1.8 (out now) and I'll look at fixing up the Greater Insistent Door Knocker.

**Comment by MrPrimate** [comment]
Both issues now resolved as of v0.1.9
