### ISSUE TITLE
Error with barbarian when importing

### ISSUE THREAD

**Issue by gridstop** [MrPrimate/pathmuncher#8]
I've been seeing an error related to a uuid, possibly from the Instinct when trying to import a barbarian. The only notable thing he has is the dragon instinct, silver dragon. I updated to the latest 0.1.15 as well.

Json of the character for importing:

{"success":true,"build":{"name":"Bob","class":"Barbarian","level":1,"ancestry":"Human","heritage":"Half-Elf","background":"Raider","alignment":"LN","gender":"M","age":"29","deity":"Gorum","size":2,"keyability":"str","languages":["Common","Elven"],"attributes":{"ancestryhp":8,"classhp":12,"bonushp":0,"bonushpPerLevel":0,"speed":25,"speedBonus":5},"abilities":{"str":18,"dex":14,"con":14,"int":10,"wis":12,"cha":10},"proficiencies":{"classDC":2,"perception":4,"fortitude":4,"reflex":2,"will":4,"heavy":0,"medium":2,"light":2,"unarmored":2,"advanced":0,"martial":2,"simple":2,"unarmed":2,"castingArcane":0,"castingDivine":0,"castingOccult":0,"castingPrimal":0,"acrobatics":0,"arcana":0,"athletics":2,"crafting":0,"deception":0,"diplomacy":0,"intimidation":2,"medicine":2,"nature":2,"occultism":0,"performance":0,"religion":0,"society":0,"stealth":0,"survival":0,"thievery":2},"feats":[["Intimidating Glare",null],["Half-Elf",null,"Heritage",1],["Nimble Elf",null,"Ancestry Feat",1],["Sudden Charge",null,"Class Feat",1]],"specials":["Rage","Low-Light Vision","Dragon Instinct","Silver","Draconic Rage (Instinct Ability)","Half-Elf"],"lores":[["Sailing",2]],"equipment":[["Bedroll",1],["Rations",2],["Flint and Steel",1],["Chalk",10],["Waterskin",1],["Soap",1],["Rope",1],["Backpack",1],["Torch",5]],"specificProficiencies":{"trained":[],"expert":[],"master":[],"legendary":[]},"weapons":[{"name":"Maul","qty":1,"prof":"martial","die":"d12","pot":0,"str":"","mat":null,"display":"Maul","runes":[]},{"name":"Greatsword","qty":1,"prof":"martial","die":"d12","pot":0,"str":"","mat":null,"display":"Greatsword","runes":[]}],"money":{"pp":0,"gp":2,"sp":5,"cp":0},"armor":[{"name":"Chain Mail","qty":1,"prof":"medium","pot":0,"res":"","mat":null,"display":"Chain Mail","worn":true,"runes":[]}],"focus":{"focusPoints":0},"spellCasters":[],"formula":[],"pets":[],"acTotal":{"acProfBonus":3,"acAbilityBonus":1,"acItemBonus":4,"acTotal":18}}}

Error screenshot from Firefox debug:

![pathmuncher_barbarian_error](https://user-images.githubusercontent.com/783880/229397720-d472e958-a4d4-40e5-9f42-394f0506152b.png)

**Comment by MrPrimate** [comment]
Should be fixed in the v0.2.0 release, out now!
